name: 5156 Bot Report
on:
  schedule:
    - cron: '0 14 * * *'  # 21:00 WIB
    - cron: '0 1 * * 6'   # 08:00 WIB Sabtu
  workflow_dispatch:      # Tombol untuk tes manual

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install axios firebase-admin
      - env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node bot.js
